services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TotoJe100%SilnéHeslo!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/lib/mssql/data
    healthcheck:
        test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 15s
  web:
    build:
      context: .
      dockerfile: MVC_projekt_Skolni_portal/Dockerfile
    image: mvc_projekt_skolni_portal
    ports:
        - "3000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: >-
        Server=db;Database=SkolniPortalZnamkyDb;
        User=sa;Password=TotoJe100%SilnéHeslo!;
        TrustServerCertificate=True


volumes:
  sqldata:
